# Appium Server
appium_server=http://127.0.0.1:4723

# iOS Device Config
platform_name=iOS
platform_version=17.0
device_name=iPhone 17
udid=BF288222-4428-4E67-8878-2DAC2732FE3A
automation_name=XCUITest

# App Config
bundle_id=com.yumealz.uat
no_reset=true
show_xcode_log=true
wda_startup_retries=1

# Wait Config
explicit_wait=30
implicit_wait=10